>AT1G47670.1 | Symbols: no symbol available | no full name available | chr1:17536625-17539719 REVERSE LENGTH=2002
ACCATTATAAATAATCATGTCATGTTCTTTAATTATC-----------------------
--AACTTTGATTGTCATTTAATTGTAAATTTCGTTAGTTAATCTGTCCTCTTCTTGTAAT
TAAAT-----------------AAAAATTTGTTTCAATACCAATAAAG--------TTGT
CCTAAAAAAAACCACCCCTCTAAATAG---------------------------------
--------------------------------------------------GGAGTGAGTG
AGAGAGAGAGTGATAGTGAGAACAAAAAAAAAACATCATTTCTTC---------------
------------------------------------------------------TCGCAC
TCTTCACCTGCTCCAATGGACGAAAGACCCGAGACAGAGCTAATATCAATACCAGCCACA
CCACGAGTTTCAACACCGGAGATTCTAACTCCCTCCGGTCAAAGATCACCTCGT------
-------------------------------------------------CCGGCCACCAA
ACCATCGTCGGCGACATGGACTCCGACTTCGTT---------------------------
----------------CA--------TATCACCGAGGTTCTTGAGTCCGATTGGTACACC
AATGAAACGAGTTCTTGTGAACATGAAAGGGTATCTTGAA------GAAGTTGGTCATCT
-----------------CACTAAGCTAAACCCACAAG-----------------------
------------ATGCTTGGCTTCCAATCACTG--------AATCTCGTAATGGAAACGC
TCATTACGCTGCTT---TTCAC---------------AATC---------------TCAA
CGCTGGTGTTGGTTTT--------------CAAGCCCTTGTTCTTC--------------
-------------------------------------CCGTCG-----------------
------------CGTTTGCGTT--------------------------------------
--TCTTGGCT--------------------------------------------------
------------------------------------------------------------
----------------------GGAGTTGGGGAATACTGTCTTTAACAATAGCATATTGC
TGGCAAC--TCTACACACTGTGGATTCTGGTTC---AGTTGCACGAAGCTGTCCCCGGGA
AACGCTACAATCGAT------------------------ATGTCGAGCTTGCACAAGCTG
CTTTTGGAGAAAGG------TTAGGAGTATGGCTTGCATT---------GTTTCCTACGG
TTTACTTATCAGCA--GGAACCGCGACAGCGCTGATTC----TGATCGGTGGAG------
------------------------------------------------------------
---------AGACAATGAAACTC------TTCTTCCAGATAG--------------TTT-
--------GCGGTCCATTATG--CACCTCGAATCCGTTAACAACAGTTGAATGGTATTTG
------GTGTTTACATCTCTCTGCATCGTTCTGTCTCAGCTACCAAACCT-----CAATT
CTATTGCGGG-------ACTCTCCTTAATAGGAGCAG---------------TGACTGCA
ATAACTTAC-TCCACAATGGTTTGGGTTCTCTCTGTGAGCCAACCAAGACCA------GC
CACTATCTCATACGAGCCTCTTTCTATGCCTT-----------CGACT------------
---------------TCTGGTTCACTCTTCGCTGTTTTGAATG--------------CTC
TTGGCATTAT-----------------AGCTTTTGCCTTCAGAGGT--------------
------------------------------------------------------------
-----------CACAACTTGGTTTTGGAAAT-----------------------------
------------------------------------------------------------
-----------------------------------TCAGTCGAC--------------GA
TGCC-------------------ATCAACGTTT---------------------------
-----AAGCATCCTG-------------CTCACGTACCAATGTGGAGAGGA---------
--------------------GCCAAAATCTCTTACTTCCTCATTGCTCTG-TGTATCTTT
CCAATCTCCATCGGAGGCTTTTGGGCTTATG-----------------------------
---------------GGAACCTTATGCCTTCAGGAGGTATGCTTGCTGCTTTGTATGCAT
TCCACATTCACGATATCCCG-----------------------------AGAGGCT----
---TA---------TTAGCGACGGCATTTCTCCTAGTAGTCTTCA---------------
---GCTGCTTGAGCAGTTTTCAGATAT--------------------ACTCCATG-----
-------------CCTGCCTTTGACAGCTTTGA---------------AGCTG----GCT
ACACAAGCAGAA-----------------------------------CCAACAAGCCGTG
TTC---GATTTGGGTCAGATCAGGTTTCCGAGTCTTTTTTGGTTTTGTCTCGTTTTTCAT
CGGTGTTGCTCTCCCTTTTCTGTCTAGTCTTG----------------------------
----CGGGGTTGCTCGGTGGACTCACTCTC---C-CGGTCACATTTGCTTATCCTTGCTT
CATGTGGGTCTTGATTAAG--AAACCGGCGA-----------------------------
---------AATACAGTTTCAATTGGTATTTCCATTGGGGATTAGGTTGGTTGGG-AGTT
GCATTCAGCTTGGCATTCTCCATAGG--TGGGAT---CTGGAGTATGGTTA--CCAATGG
ACTTAAGCTCAAGTTCTTC-------------------------------AAGCC-----
------------------------------------------------------------
---------------------------------------------------------GCC
TAACTAAGTAGTA---ATAGCCTATGTGGTTTTGTTTGGTTGGGAAGTTTGAAGTTTTAA
GAGATTTTGTA-------------------------------------------------
------------------------------------------------------------
--------TTTCTGTGTTTTGTTTAAGAGTGCCTATGTTTTGAAGTTGGAACAAT-----
-----------------------GTAAT-----GTGTATTATAATTCAGTAAGCTT----
--------TTC-----------------------------------AATATAAAGAATTT
GGAATTTTGAAGAATCACACTTGTGTGCCTCTGTTGAATCCCTAGCTGGA----------
------ATTTTC------------------------------------
>AT1G25530.1 | Symbols: no symbol available | no full name available | chr1:8964544-8967562 REVERSE LENGTH=1777
-----------------GAAAAAAAGAAGAGCCCAAC-----------------------
--AAGTGACATTAATTTAAGATCTTAAAGAAAATTACATAAACTTTATTATTATAGCAAA
AAAAT-----------------AAAA----------------------------------
-----------------CTCAAAACACCCT------------------------------
------------------------------------------------TAAAAGCGCCTA
GTTGTCCACATTTTTAGGGAACTGAGATT-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------GTCTCACTACACT---------------------------
----------------TG--------CAAAAAAGACACGCA-------------------
--------------------------------ATGGTCT----------CTAGTTCTCCG
GTTTCTCCGTCTAAGGAAACTGACCGGAAGTCCGGCG-----------------------
------------AGAAATGGACGGCGGAAGATC--------CATCACGGCCAGCCAAGTG
GTGGTACTCCACCT---TCCAC---------------ACCG---------------TCAC
CGCCATGATTGGCGCG--------------GGAGTCCTCAGCCTTC--------------
-------------------------------------CTTATG-----------------
------------CCATGGCTTA--------------------------------------
--CCTTGGCT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCAGGGACCTTTGTGTTGGCAATGACGTG--GG
GACTGACCCTAAACACTATGTGGCAAATGGTGC---AGCTCCATGAGTGTGTACCGGGAA
CCCGGTTTGACCGGT------------------------ATATCGATCTAGGCCGGTATG
CTTTTGGCCCAAAA------CTTGGCCCATGGATCGTCCT---------C-CCTCAACAG
CTAA-TCGTCCAGGTCGGCTGCAACATCGTTTACATGG----TGACAGGAGGCA------
------------------------------------------------------------
---------AGTGCTTGAAGCAG------TTCGTGGAGATCA--------------CTT-
--------GTTC-CACCTGTA--CAC--------CGGTACGACAGTCGTACTGGATCCTC
------GGCTTCGGTGGAGTCCATTTCATTCTCTCCCAGCTCCCTAACTT-----CAACT
CCGTTGCCGG-------AGTCTCCCTGGCTGCCGCCG---------------TCATGTCT
CTCTGCTAC-TCGACGATAGCTTGGG----------GAGGAAGTATCGCACATGGAAGAG
TGC--------CTGACGTGAGC--TATGATTACAAGGCGACGAATCCG------------
---------------GGTGACTTCACATTCCGAGTCTTTAATG--------------CGT
TAGGTCAGAT-----------------CTCATTCGCTTTCGCTGGC--------------
------------------------------------------------------------
-----------CACGCTGTGGCTCTAGAGAT-----------------------------
------------------------------------------------------------
-----------------------------------TCAAGCCAC--------------GA
TGCC-------------------TTCCACTCCT---------------------------
-----GAGAGACCAT-------------CCAAGGTGCCCATGTGGCAAGGA---------
--------------------GTGATCGGAGCTTACGTGGTCAACGCCGTT-TGCTATTTT
CCTGTGGCTCTGATATGCTATTGGGCCTTTG-----------------------------
---------------GTCAAGACGT---GGACGACAATGTGC------------------
-------TGATGAATCTACA-----------------------------GAGACCAGCTT
GGCTC---------ATTGCTGCTGCTAATCTCATGGTTGTTGTCC---------------
---ATGTCATTGGTAGCTACCAAGTGT--------------------TTGCTATG-----
-------------CCTGTCTTTGATCTTTTGGA---------------GAGGATGATGGT
TAACAAATTTGGTTT----------------------------TAAGCATGGAGTTGTTC
TGA---GGTTT-------TTCA----CTCGAACTATTTATGTCGCATTTACATTGTTCAT
TGGAGTGAGTTTCCCCTTCTTTGGAGACCTTC----------------------------
----TAGGCTTCTTTGGAGGATTTGGTTTTGCAC-CTACTTCTTTCTTCCTCCCAAGTAT
AATGTGGCTTATCATCAAG--AAACCAAGGA-----------------------------
---------GATTCAGCGTCACCTGGTTCGTCAATTGGATCTCCATTATCGTAGG-AGTG
TTCATAATGTTAGCGTCAACAATTGG--AGGGTT---GAGGAACATCATTG--CAGATTC
TTCTACTTATAGTTTCTACGCTTAA-----------------TATTGAATAGATCTTGTA
CACTAAAGCATGAATCATTGGAT------CATCTAAATTAAAAAGTGTAGGAA-------
---TAAATCATCTA-------------------------------------------AAT
TAACTGATGGTCGGATCGAGTT-AGAGAGTGATGTATAATGCTACTTGTTCAATAAGACA
TATTACTAGTAGAT----------------------------------------------
------------------------------------------------------------
---GTGTATTATGTTGCATCATATGTGGTCTTCTTAACATCAAACCTAAGATCCTCTACA
CTTGTC-----------CTAGTCTTTCT-----ATTTCTTATCTTACAAATAATTT----
TGTTATACGAT-----------------------------------AATAAAACAAAACC
ACATTTTGT---------------------------------------------------
------------------------------------------------
>AT1G61270.1 | Symbols: no symbol available | no full name available | chr1:22599541-22602252 REVERSE LENGTH=1592
------------------CTTCAATGAGGTAAAAGTC-----------------------
--AACTTTTATTCCCTCTCTATCTGTCTCTCTATCTCTCGTGCACACAACTTTT------
---AG-----------------AAAGATTG------------------------------
----------------TCTCGCAAGTC---------------------------------
------------------------------------------------------------
----ACAATATTCCTAAGTTGACAATGAA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------AGGAATCCCAAGTTCGT---------------------------
----------------CAAACCAGATCCTAAACCAAGATC--------------------
--------------------------------TTGTTG--------AGGATCAATCATTT
------------------------------GAGCTGG-----------------------
------------AAGATTGGCTTCCAATTACAG--------CATCACGAAATGCTAATTG
GTACTATTCAGCTT---TCCAC---------------AACG---------------TCAC
TGCCATAGTTGGTGCT--------------GGAGTTCTTGGTCTCC--------------
-------------------------------------CTTACG-----------------
------------CCATGTCAGA--------------------------------------
--ACTTGGAT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCTGGAGTTGTGGTGTTGATCCTGTCATG--GG
TCATAACGTTATACACGTTCTGGCAAATGATTG---AGATGCACGAAATGTTTGAAGGGA
AACGGTTTGATAGGT------------------------ACCACGAGCTAGGACAAGCAG
CCTTTGGCAAAAAG------CTTGGTTTGTACATCGTCGT---------G-CCGCTTCAA
CTTC-TTGTTGAGACAAGTGCTTGCATAGTGTATATGG----TGACAGGAGGTG------
------------------------------------------------------------
---------AATCACTGAAAAAG------ATTCATCAAC-----------------TTTC
TGTGGGAGACTA-CGAGTGTA--GAA--------AGTTGAAAGTTCGACACTTCATTTTG
------ATCTTTGCCTCTTCACAGTTTGTGCTTTCCCTTCTTAAAAATTT-----CAACT
CCATTTCCGG-------TGTCTCTTTGGTAGCTGCCG---------------TCATGTCT
ATGAGCTAT-TCCACAATTGCTTGGGTAGCTTCACTGACAAA---------G------GG
TGT---CGCGAACAATGTTGAA--TATGGATATAAAAGAAGAAACAAC------------
---------------ACCTCAGTGCCATTAGCCTTCTTAGGCG--------------CAT
TGGGGGAGAT-----------------GGCTTTTGCGTATGCAGGT--------------
------------------------------------------------------------
-----------CACAATGTTGTTTTAGAAAT-----------------------------
------------------------------------------------------------
-----------------------------------TCAAGCAAC--------------GA
TTCC-------------------ATCAACACCA---------------------------
-----GAAAATCCAT-------------CAAAACGACCCATGTGGAAGGGA---------
--------------------GCCATTGTAGCCTATATTATTGTAGCTTTC-TGTTACTTC
CCTGTGGCCCTTGTAGGGTTTTGGACATTCG-----------------------------
---------------GAAACAACGT---TGAAGAAAACATTC------------------
-------TCAAAACACTCCG-----------------------------GGGCCCGAAGG
GACTT---------ATAATTGTGGCCAACATTTTTGTGATTATAC---------------
---ATCTCATGGGAAGCTACCAGGTGT--------------------ACGCAATG-----
-------------CCCGTGTTTGACATGATCGA---------------ATCTGTAATGAT
AAAGAAATGGCACTT----------------------------CAGTCCAACAAGAGTTC
TAC---GGTTT-------ACCA----TCCGTTGGACTTTTGTGGCCGCCACGATGGGGAT
AGCAGTCGCTCTACCGCATTTCAGTGCTTTGC----------------------------
----TGTCATTTTTTGGAGGATTCATATTTGCCC-CGACCACATACTTTATCCCTTGCAT
CATATGGCTGATCCTGAAG--AAACCAAAGA-----------------------------
---------GATTTAGTCTATCATGGTGTATCAATTGGATTTGCATCATTCTTGG-GGTT
CTAGTGATGATTATAGCACCTATTGG--GGGACTCGCCAAATTAATGAATGCTTTAAAGC
AACCCGACTCCAGTTGCAA-----------------------------------------
------------------------------------------------------------
---------------------------------------------------------AAG
CACCTAAATATTGTACTGAATT--------------------------------------
---TTCTTGTAGGT----------------------------------------------
------------------------------------------------------------
------------------------------------------AACACAAGTTTTTCTCTA
GTAGTTTGATATATTGTTTAATCATGGC-----------TTCACTATAACAAACTCTGAG
TGTGAATCTGT-----------------------------------ATTGAAACAAATGT
ATGTGG------------------------------------------------------
------------------------------------------------
>AT3G01760.1 | Symbols: LHT6 | lysine-histidine-like transporter 6 | chr3:273248-275304 FORWARD LENGTH=1453
--------------------------------AAAAC-----------------------
--AGATA-----------------------------------------------------
---GG-----------------AAAGATTG------------------------------
----------------CCTCACAAGTC---------------------------------
------------------------------------------------------------
----ACAACATTCCTAAGTTTGCAATGGC-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------GGGAATCCCAGATCATA---------------------------
----------------TC--------CAAGACCAACATCTT-------------------
--------------------------------GTGGAGG-------AGGATCAACCCTTT
------------------------------GATCTGG-----------------------
------------AAGATTGGCTTCCAATCACAG--------CATCAAGGAATGCCAATTG
GTATTATTCAGCTT---TCCAC---------------AACG---------------TCAC
TGCCATTGTTGGTGCT--------------GGCGTTCTCGGTCTTC--------------
-------------------------------------CTTACG-----------------
------------CCATGTCAGA--------------------------------------
--GCTTGGAT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCTGGGGTTGTGGTGTTGATCCTGTCATG--GG
TGATCACGTTATACACCCTCTGGCAAATGATTG---AGATGCATGAGATGTTTGAAGGGC
AACGGTTCGATAGGT------------------------ACCATGAGCTGGGTCAGGCAG
CCTTTGGTAAAAAG------CTTGGTTTGTACATCATCGT---------G-CCCCTACAA
CTAC-TTGTCGAGATCAGTGTGTGCATAGTCTATATGG----TCACTGGAGGTA------
------------------------------------------------------------
---------AATCCCTGAAGAAT------GTACATGACCTTG--------------CTTT
GGGAGATGGTGA-CAAGTGCA--CAA--------AGCTTAGAATTCAACACTTCATTTTG
------ATCTTTGCCTCTTCACAGTTCGTGCTCTCCCTTCTTAAGAACTT-----CAACT
CCATTTCTGG-------TGTCTCCTTGGTAGCTGCTG---------------TCATGTCT
GTCAGCTAT-TCTACAATTGCTTGGGTAGCCTCGCTGAGGAA---------G------GG
TGC--CACCACCGGGAGTGTAGAGTACGGCTATAGAAAAAGAACAACC------------
------------------TCAGTGCCATTAGCCTTCTTAAGTG--------------CAC
TGGGTGAAAT-----------------GGCTTTTGCGTACGCAGGT--------------
------------------------------------------------------------
-----------CATAACGTTGTTTTGGAAAT-----------------------------
------------------------------------------------------------
-----------------------------------TCAAGCAAC--------------GA
TCCC-------------------ATCAACACCA---------------------------
-----GAGAACCCAT-------------CAAAACGACCCATGTGGAAGGGA---------
--------------------GCGGTTGTAGCCTATATCATTGTAGCTTTC-TGCTACTTC
CCTGTGGCACTTGTAGGTTTCAAGACCTTTG-----------------------------
---------------GAAACAGTGT---TGAAGAGAGCATCC------------------
-------TCGAATCACTAAC-----------------------------AAAACCAACGG
CACTT---------GTCATTGTGGCCAACATGTTTGTGGTCATAC---------------
---ATCTCTTGGGAAGCTACCAGGTGT--------------------ATGCGATG-----
-------------CCCGTGTTTGACATGATCGA---------------ATCTGTAATGAT
AAGGATATGGCACTT----------------------------CAGTCCAACAAGAGTTC
TAC---GGTTT-------ACCA----TCCGATGGACTTTTGTGGCCGCCACGATGGGAAT
AGCGGTCGGTTTACCGTATTACAGCGCATTGC----------------------------
----TGTCATTTTTTGGGGGATTTGTGTTCGCCC-CGACCACATACTTTATCCCATGCAT
CATGTGGCTGATCCTAAAG--AAACCAAAGA-----------------------------
---------GATTTAGTCTCTCATGGTGTATGAACTGGTTTTGCATCATTTTTGG-GCTT
GTGCTGATGATCATAGCACCTATTGG--GGGACTGGCCAAACTAATC-------------
-------TATAA------------------------------TATTCAAAAGGGCACTCT
ACCTAATTCAAGATGCA-------------------------------------------
---------------------------------------------------------ACT
TACCTAAACACTG---ACGATT--------------------------------------
---GCCTTGTAGGT----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------AACATAAATTGGTT
GGAC--------------------------------------------------------
------------------------------------------------
>AT1G67640.1 | Symbols: no symbol available | no full name available | chr1:25351906-25354026 REVERSE LENGTH=1666
------------------------ATTGTCACAAGGC-----------------------
--ACATTTCAATCCTCAGG-----------------------------------------
---AA-----------------AGAAATTGCCTT--------------------------
----------------GCTCTTGAATC---------------------------------
------------------------------------------------------------
---------CTTTTGGTTCTCATCATCTA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------ATTGTGTCCCACATTTTT---------------------------
----------------TTCTGTTCTTCAAAGCCAAAATAAG-------------------
--------------------------------ATGGAGA-------AAAGTCAATCGTCT
CCAACCAAGGACGCGTCCACAAAGCAGAAGAATGTAG-----------------------
------------ACGATTGGTTACCGATAACAT--------CCTCTAGAAATGCCAAGTG
GTGGTACTCTGCGT---TTCAC---------------AATG---------------TCAC
CGCCATGGTCGGGGCT--------------GGTGTACTCAGCTTAC--------------
-------------------------------------CTTACG-----------------
------------CCATGTCTAA--------------------------------------
--TCTTGGAT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCTGGAGTGACAATAATGATAATGTCATG--GC
TGATAACATTCTACACACTATGGCAGATGGTGC---AAATGCACGAGATGGTTCCAGGGA
AGAGGTTCGACAGGT------------------------ACCACGAATTAGGCCAACACG
CGTTTGGGGAGAAG------CTCGGACTATGGATCGTGGT---------G-CCACAACAA
CTAA-TCGTTGAAGTAGGTGTGGATATTGTGTACATGG----TTACGGGAGGGA------
------------------------------------------------------------
---------AGTCATTGAAAAAA------ATTCATGACCTTC--------------TTT-
--------GCAC-CGATTGCA--AAA--------ATATAAGAACTACATATTGGATCATG
------ATCTTCGCTTCCATACACTTTGTTCTTGCTCATCTCCCTAATTT-----TAACT
CCATATCTAT-------CGTCTCCCTTGCTGCTGCCG---------------TTATGTCT
TTGAGCTAC-TCGACAATCGCTTGGGCAACCTCGGTGAAGAA---------A------GG
AGTTCATCCAAA-----TGTAGACTACTCGTCTAGAGCATCTACAACC------------
---------------TCAGGAAATGTATTCAACTTCTTGAATG--------------CAC
TAGGAGATGT-----------------GGCATTTGCGTATGCAGGT--------------
------------------------------------------------------------
-----------CACAACGTTGTGTTGGAGAT-----------------------------
------------------------------------------------------------
-----------------------------------ACAAGCTAC--------------TA
TTCC-------------------TTCAACACCT---------------------------
-----GAGAAACCAT-------------CAAAGATTGCAATGTGGAAAGGA---------
--------------------GTAGTAGTTGCATACATCGTTGTTGCCATA-TGCTACTTT
CCCGTTGCATTTGTTTGCTACTATATCTTTG-----------------------------
---------------GAAACAGTGT---GGACGACAATATTC------------------
-------TCATGACGTTGGA-----------------------------GAAACCCATCT
GGCTT---------ATCGCCATTGCTAACGCATTCGTGGTTGTCC---------------
---ATGTCATTGGAAGCTACCAAATAT--------------------ACGCAATG-----
-------------CCGGTCTTTGACATGCTCGA---------------AACCTTTTTGGT
AAAGAAGATGATGTT----------------------------CGCTCCTTCCTTCAAAC
TCC---GCTTC-------ATCA----CTCGTACTCTATATGTTGCTTTCACGATGTTCGT
TGCCATATGCATCCCATTTTTTGGTGGATTGC----------------------------
----TCGGGTTTTTCGGAGGATTCGCCTTTGCCC-CAACAACTTACTATCTACCATGCAT
CATGTGGCTTTGTATCAAG--AAACCAAAGA-----------------------------
---------AGTATGGATTGTCTTGGTGTATTAATTGGTTTTGCATAGTAGTTGG-TGTT
ATATTGACGATCCTAGCTCCCATTGG--TGGCCT---CAGAACCATTATTA--TCTCAGC
CAAAAACTACGAATTCTTCTCTTGAAGACCACTTTAT-----TTTTCGAACCCTTTGTTT
CCATCAATCCAATGTTGTTTTGACAATTT-------------------------------
---------------------------------------------------------CAT
TTTCGAAACACAA---CTGGTC-------------------------------------A
TGTGTCTCATATAT----------------------------------------------
-----------------------------------------------------------A
CTTTCATTTCGCCATTTGTTCAGTGGCCAATAATTAATGGTCAATTCTAAA---------
-------------------------GGT-----TTGTATTTTTTTTTATAAAATT-----
TGATATAATGT-----------------------------------ATTATCCAAAATAT
ATAT--------------------------------------------CA----------
------TCTTTAAAATCAGTTCGA------------------------
>AT1G24400.1 | Symbols: AATL2, ATLHT2, LHT2 | lysine histidine transporter 2, ARABIDOPSIS LYSINE HISTIDINE TRANSPORTER 2, AMINO ACID TRANSPORTER-LIKE PROTEIN 2 | chr1:8651407-8653915 REVERSE LENGTH=1836
GGGTAAATTAGTATTTAAATTGGTCTAAGCATGAAAC-----------------------
--AGCTTCCAGCCGATGGTGCCTTATGCCTCGGGCAAAAAAAAAGACCAAACACACTAAA
CAAAACTACCAAACAAACTAACAAACATTCCCTTCAAATTCGGAAAAGTCAGAATCTCAT
CACCTATTTATTACACTCTCATAAACG---------------------------------
-------------------------------------------------CTAACAAATCG
TTGAATAGAATAATTAAGCAGGTAAAATC-------------------------------
------------------------------------------------------------
----------CTAAACCGTCAGAGAATATCTATCCTCCTCTTAAATATCACTCTT-----
------------------------------------------------------------
-------------------------------------------------ATCTTTATCCT
CCTAAAATCTTCTTAATTGTATCTAATCTCTTT---------------------------
----------------CT--------CAAAAACCAAACACTATCTCTCGATTAT------
-------------------ATCACAAGGAGATATGGGGA-------ACAGTGAAATGTCA
GCGAGTGAGGTTGCGGCGGCCAAGCAGAAGAACGTCG-----------------------
------------ACGATTGGTTACCGATCACAT--------CTTCCAGAAACGCTAAGTG
GTGGTACTCTGCTT---TTCAC---------------AATG---------------TCAC
CGCCATGGTTGGTGCT--------------GGTGTTCTTAGCTTGC--------------
-------------------------------------CCTACG-----------------
------------CTATGTCCAA--------------------------------------
--TCTCGGAT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCTGGAGTGACGATTATGGTGATGTCATG--GA
TCATAACGTTGTACACACTGTGGCAAATGGTGG---AGATGCATGAGATTGTTCCAGGGA
AGAGGCTTGATAGGT------------------------ATCACGAGCTAGGTCAACACG
CTTTTGGTGAAAAG------CTTGGCCTATGGATCGTCGT---------G-CCGCAGCAG
CTTA-TCGTGGAGGTCGGTGTTGACATCGTTTATATGG----TCACAGGAGGAG------
------------------------------------------------------------
---------CATCCCTCAAGAAA------GTCCATCAACTAG--------------TCT-
--------GTCC-CGATTGCA--AAG--------AGATCAGAACTACGTTTTGGATCATG
------ATCTTTGCTTCCGTCCACTTTGTTATCTCTCACCTTCCCAATTT-----CAACT
CTATCTCCAT-------CATCTCACTTGCCGCGGCTG---------------TTATGTCC
TTAACTTAC-TCAACTATTGCTTGGGCTGCATCCGTGCACAA---------A------GG
GGTACATCCAGA-----TGTGGACTACTCTCCTAGAGCATCAACCGAT------------
---------------GTTGGAAAAGTATTCAACTTCTTGAATG--------------CGT
TGGGAGATGT-----------------GGCTTTTGCTTATGCAGGT--------------
------------------------------------------------------------
-----------CACAACGTTGTGTTGGAGAT-----------------------------
------------------------------------------------------------
-----------------------------------TCAGGCCAC--------------AA
TCCC-------------------TTCGACTCCG---------------------------
-----GAGATGCCAT-------------CCAAGGTCCCAATGTGGAGAGGA---------
--------------------GTTATTGTAGCCTACATTGTAGTCGCCATC-TGTTACTTC
CCTGTAGCATTCCTCGGCTATTATATCTTTG-----------------------------
---------------GAAACAGCGT---TGATGACAACATCC------------------
-------TCATCACTTTGGA-----------------------------GAAGCCTATCT
GGCTT---------ATTGCTATGGCTAACATGTTCGTGGTTATCC---------------
---ATGTCATTGGAAGCTATCAGATAT--------------------TTGCAATG-----
-------------CCAGTTTTTGACATGCTCGA---------------AACCGTTTTGGT
CAAAAAGATGAATTT----------------------------CAATCCTTCTTTCAAGC
TCC---GCTTC-------ATTA----CTCGTAGTCTTTACGTCGCTTTCACGATGATTGT
TGCGATATGCGTCCCGTTTTTCGGTGGACTAC----------------------------
----TCGGCTTCTTTGGAGGATTCGCCTTTGCCC-CAACAACTTACTACCTTCCATGCAT
TATGTGGCTCGTTCTCAAG--AAACCAAAGA-----------------------------
---------GGTTTGGTCTATCTTGGACAGCTAACTGGTTCTGCATCATAGTAGG-AGTT
CTTTTGACGATCCTTGCCCCAATTGG--AGGACT---CAGAACCATCATTA--TCAACGC
CAAGACCTACAAGTTCTTCTCT--------------------TAGATGGATCACTTTTTT
TTGT--------------------------------------------------------
---------------------------------------------------------AAC
CGCGCAACCGAAAAATAAAATC----ACGGCATGTCTAATTTTATGTGACTGTCCGTTTA
AGTAAATTTTATGT----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------TTTCATTGTAGTTAAGACAATTATCTT
TGGTTTCTTTT-----------------------------------GATAATAAACTCTT
------------------------------------------------------------
--------TTTCAAATAATT----------------------------
>AT1G48640.1 | Symbols: no symbol available | no full name available | chr1:17986303-17989163 FORWARD LENGTH=1589
-----------------TAATGAGATTACCGGAGAAC-----------------------
--AAAAGT----------------------------------------------------
---GT-----------------AAGAGTTA------------------------------
------------------TCGCAGGTT---------------------------------
-----------------------------------------------------------G
TCGGATAAAATGTATATTCAGATGACAGA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------TGGAGTTCC---TCCGC---------------------------
----------------CA--------CCAGAGCAAAGTTCGTTAGACCACC---------
--------------------------------GGATTGAC------GAGCTTGA------
--------------------GAGACAGAAAGAGATCG-----------------------
------------ATGATTGGCTTCCGATAACTT--------CATCGAGAAACGCGAAATG
GTGGTACTCCACGT---TTCAC---------------AACG---------------TGAC
TGCCATGGTTGGAGCT--------------GGCGTCCTTGGTCTCC--------------
-------------------------------------CTTTCT-----------------
------------TCATGGCCCA--------------------------------------
--ACTCGGAT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCAGGCATAGCAGTCCTGATACTATCATG--GA
TAATAACACTTTACACGTTATGGCAAATGGTGG---AGATGCATGAGATGGTTCCCGGAA
AACGCTTTGATCGCT------------------------ATCATGAACTTGGTCAGTTCG
CATTTGGCGAACGT------CTTGGCCTTTATATTATCGT---------C-CCTCAGCAA
ATCA-TTGTTGAAGTTGGAGTATGCATAGTTTATATGG----TCACCGGAGGAC------
------------------------------------------------------------
---------AGTCGTTGAAGAAG------TTTCACGAAATCG--------------CCT-
--------GTCA-AGATTGCT--CAC--------CGATCAGACTTTCTTTCTTCATAATG
------ATATTTGCTTCTTCTCATTTCGTTTTATCTCATCTCCCAAACTT-----CAACT
CCATCTCGGG-------TGTCTCTCTTGTTGCGGCCG---------------TCATGTCT
CTTAGTTAT-TCGACAATTGCGTGGACAGCAACAGCCGCAAA---------G------GG
CGT---TCAAGAAGATGTTCAA--TATGGTTACAAATCAGGCACGACC------------
---------------GCGTCAACAGTCTTAAGCTTCTTTACGG--------------GAC
TTGGGGGCAT-----------------TGCGTTTGCATATGCAGGT--------------
------------------------------------------------------------
-----------CACAATGTGGTGCTTGAGAT-----------------------------
------------------------------------------------------------
-----------------------------------CCAAGCAAC--------------GA
TACC-------------------CTCTACACCA---------------------------
-----AGTAACCCTT-------------CTAAAGGTCCTATGTGGAGAGGA---------
--------------------GTGGTGGTGGCTTACGTGGTTGTGGCCTTG-TGTTATTTC
CCCGTTGCTTTGGTTGGCTATGGAGTTTTCG-----------------------------
---------------GAAACGCGGT---TTTGGATAACGTGT------------------
-------TGATGTCGCTCGA-----------------------------AACGCCCGTTT
GGGCC---------ATTGCAACTGCTAACTTGTTCGTCGTTATGC---------------
---ATGTCATTGGTAGTTACCAGATAT--------------------TCGCGATG-----
-------------CCGGTTTTCGACATGGTGGA---------------GACATTTCTGGT
TAAGAAACTGAATTT----------------------------CAAACCCTCTACAGTTC
TTC---GTTTC-------ATTG----TACGAAATGTTTATGTTGCTTTAACGATGTTCAT
TGGGATAATGATACCGTTCTTTGGGGGCCTTC----------------------------
----TCGCTTTCTTTGGAGGATTTGCGTTTGCTC-CAACATCGTATTTTCTTCCTTGCAT
AATGTGGCTGCTAATCTAT--AAACCAAAGA-----------------------------
---------GGTTTAGCCTGTCGTGGTGGACGAATTGGGTATGTATAGTGCTTGG-AGTT
GTTTTGATGATCTTATCATCAATAGG--AGGGTT---AAGGCAAATCATTA--TTCAGTC
CAAAGATTACAGTTTCTTCTCT--------------------TGATTAATTTCTCCCTTC
TAACA-------------------------------------------------------
---------------------------------------------------------CAA
TCTACAATAGAAAAAAATGATT-----------------------TTTCTTTATCATATA
CATATATTATCAAT----------------------------------------------
------------------------------------------------------------
--------TTTTCATCATGTAT------------TTATCCCGAATAAGAAGCTGCTAACT
GCAAGT-----------------GCAAA-----GTCTTCTAACTCAAATTAATCGA----
--------TCG-----------------------------------AATGATGAATGATT
GAATACA-----------------------------------------------------
------------------------------------------------
>AT5G40780.1 | Symbols: LHT1 | lysine histidine transporter 1 | chr5:16323567-16327382 FORWARD LENGTH=1897
-----------------------------CATAACTC-----------------------
--TTGTGCCCATCTCCACAAGTAGTTTGTGAAGTCAAACAAAAACTTCCACTTT------
----------------------TAAAATTT-----------------------------T
CTCTTATTTCTTTCTCTCTCATAAGTC---------------------------------
--------------------------------------------------ATAATATTCA
ACTAATTAAGTGCATATATATACGATGTA-------------------------------
------------------------------------------------------------
---TCAGTGCTTATAATCTTCATGAGGAGCTTTATATATTTAGCATAATATCTTTCAGAA
GTGTGAGGCCTTGTTAATTAAGCTCTTCTTCTCTATCT----------------------
-------------------------------------------------CTCTCTCTCCC
TCTCAACCTCTCACCATGGTAGCTCAAGCTCCT---------------------------
--------------------------CATGATGATCATCAGG------------------
--------------------------------ATGATGA-------GAAATTAG------
-------------CAGCAGCGAGACAAAAAGAGATCG-----------------------
------------AAGATTGGTTACCAATTACTT--------CATCAAGAAATGCAAAGTG
GTGGTACTCTGCTT---TTCAC---------------AATG---------------TCAC
CGCCATGGTCGGTGCC--------------GGAGTTCTTGGACTCC--------------
-------------------------------------CTTACG-----------------
------------CCATGTCTCA--------------------------------------
--GCTCGGAT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCGGGAATTGCAGTGTTGGTTTTGTCATG--GG
TCATAACACTATACACATTATGGCAAATGGTGG---AAATGCATGAAATGGTTCCTGGAA
AGCGTTTTGATCGTT------------------------ACCATGAGCTCGGACAACACG
CGTTTGGAGAAAAA------CTCGGTCTTTATATCGTTGT---------G-CCGCAACAA
TTGA-TCGTTGAAATCGGTGTTTGCATCGTTTATATGG----TCACTGGAGGCA------
------------------------------------------------------------
---------AATCTTTAAAGAAA------TTTCATGAGCTTG--------------TTT-
--------GTGA-TGATTGTA--AAC--------CAATCAAGCTTACTTATTTCATCATG
------ATCTTTGCTTCGGTTCACTTCGTCCTCTCTCATCTTCCTAATTT-----CAATT
CCATCTCCGG-------CGTTTCTCTTGCTGCTGCCG---------------TTATGTCT
CTCAGCTAC-TCAACAATCGCATGGGCATCATCAGCAAGCAA---------A------GG
TGT---TCAAGAAGACGTTCAA--TACGGTTACAAAGCGAAAACAACA------------
---------------GCCGGTACGGTTTTCAATTTCTTCAGCG--------------GTT
TAGGTGATGT-----------------GGCATTTGCTTACGCGGGT--------------
------------------------------------------------------------
-----------CATAATGTGGTCCTTGAGAT-----------------------------
------------------------------------------------------------
-----------------------------------CCAAGCAAC--------------TA
TCCC-------------------TTCAACGCCT---------------------------
-----GAGAAACCCT-------------CAAAAGGTCCCATGTGGAGAGGA---------
--------------------GTCATCGTTGCTTACATCGTCGTAGCGCTC-TGTTATTTC
CCCGTGGCTCTCGTTGGATACTACATTTTCG-----------------------------
---------------GGAACGGAGT---CGAAGATAATATTC------------------
-------TCATGTCACTTAA-----------------------------GAAACCGGCGT
GGTTA---------ATCGCCACGGCGAACATCTTCGTCGTGATCC---------------
---ATGTCATTGGTAGTTACCAGATAT--------------------ATGCAATG-----
-------------CCGGTATTTGATATGATGGA---------------GACTTTATTGGT
CAAGAAGCTAAATTT----------------------------CAGACCAACCACAACTC
TTC---GGTTC-------TTTG----TCCGTAATTTCTACGTTGCTGCAACTATGTTTGT
TGGTATGACGTTTCCGTTCTTCGGTGGGCTTT----------------------------
----TGGCGTTCTTTGGTGGATTCGCGTTTGCCC-CAACCACATACTTCCTCCCTTGCGT
CATTTGGTTAGCCATCTAC--AAACCCAAGA-----------------------------
---------AATACAGCTTGTCTTGGTGGGCCAACTGGGTATGCATCGTGTTTGG-TCTT
TTCTTGATGGTCCTATCGCCAATTGG--AGGGCT---AAGGACAATCGTTA--TTCAAGC
AAAAGGATACAAGTTTTACTCATAAACGCTATGTAATTCCACTAATTAAGAAACATATCT
TTATATTAATATATGTGTGAAG--------------------------------------
---------------------------------------------------------AAG
TTTTTAAGAGATCAACACGAGACATTTATAGAAGAATCAATGGTCTGGTCTGAATCTAAA
TGTAGCTTTTAGGG----------------------------------------------
------------------------------------------------------------
-------TTTGTATTTTCGTGTGTGTTATATATATTATATAAAACA-----------ATA
ATATTTTGCTCAAATAGGTTTTCAAAAT-----GTTTGGTTTTCTGAGGAGATTGATTCT
TTGTGTTCTCA-----------------------------------AGAAAAGAATACAT
AGATGGATATCATTCCA-------------------------------------------
------ACTTCCAAGTTATTACTATTATTATAT---------------
>AT1G71680.1 | Symbols: no symbol available | no full name available | chr1:26944671-26947219 FORWARD LENGTH=1835
-----------------------ATGACATACACAGC-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------GAATGACGAGGAGAACAAAGGA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------AGATCAACGGAC--------------------
----------------------------------------------AATAACAATCACCG
-----------------------TCAAATGGATTACA-----------------------
------------ACGATTGGTTACCAGTCACAG--------CGTCTAGAGAAGCCAAATG
GTATTACTCCGCCT---TCCAC---------------AATG---------------TCAC
GGCCATGGTTGGCGCC--------------GGAGTTCTTGGTCTCC--------------
-------------------------------------CTTTCG-----------------
------------CCATGTCACA--------------------------------------
--ACTTGGCT--------------------------------------------------
------------------------------------------------------------
----------------------GGGGACCTGGACTTGTTGCTATAATAATGTCATG--GG
CTATAACGTTCTACTCGTTATGGCAAATGGTAC---AGTTGCACGAAGCCGTTCCAGGGA
AACGGTTGGACCGTT------------------------ACCCCGAGCTAGGGCAAGAAG
CTTTTGGACCAAAA------CTAGGTTACTGGATCGTCAT---------G-CCGCAACAG
CTTC-TTGTCCAAATCGCTTCCGACATAGTCTACAACG----TGACAGGAGGAA------
------------------------------------------------------------
---------AATCTCTCAAGAAA------TTTGTCGAGCTT-------------------
-------------CTATTTCC--GAATCTCGAACATATCCGTCAGACTTATTACATCCTT
------GGATTCGCCGCGCTTCAGCTTGTCCTCTCTCAATCTCCTGATTT-----CAACT
CCATCAAGAT-------CGTCTCTCTCCTCGCCGCCC---------------TCATGTCT
TTCCTTTAC-TCAATGATAGCTTCGGTGGCGTCAATAGCAAA---------A------GG
AACGGAAC--ACCGTCCTTCAACTTACGGAGTCAGGGGAGACACGGTG------------
---------------GCCTCAATGGTCTTTGATGCATTTAACG--------------GCA
TTGGAACCAT-----------------AGCGTTTGCGTTTGCAGGA--------------
------------------------------------------------------------
-----------CACAGTGTGGTTCTTGAGAT-----------------------------
------------------------------------------------------------
-----------------------------------CCAAGCAAC--------------TA
TTCC-------------------TTCAACACCT---------------------------
-----GAAGTGCCTT-------------CCAAGAAACCAATGTGGAAAGGA---------
--------------------GTTGTTGTAGCTTACATAATCGTCATCATT-TGTTACCTT
TTTGTGGCTATCTCCGGCTATTGGGCGTTTG-----------------------------
---------------GGGCTCATGT---TGAGGATGATGTTC------------------
-------TCATTTCCTTAGA-----------------------------GAGACCAGCTT
GGCTT---------ATAGCGGCTGCTAACTTCATGGTTTTTATCC---------------
---ATGTCATAGGAAGTTATCAGGTTT--------------------TTGCGATG-----
-------------ATTGTGTTTGACACGATCGA---------------GTCTTATCTTGT
GAAAACACTGAAATT----------------------------CACTCCTTCAACAACAC
TGC---GTCTA-------GTCG----CACGTAGTACATATGTTGCATTGATTTGTCTTGT
AGCAGTTTGTATCCCCTTTTTCGGAGGTCTTT----------------------------
----TAGGGTTCTTCGGCGGTCTTGTCTTCTCAT-CAACCTCGTACTTCTTGCCTTGCAT
TATATGGTTGATAATGAAG--CGACCAAAAA-----------------------------
---------GATTTAGCGCCCATTGGTGGTGTTCTTGGGTAGCAATAGTCACTGG-TATC
TCGATAGCGATTCTTGCGCCCATTGG--AGGAAT---GAGACACATTATTC--TTTCAGC
AAGAACCTACAAGCTCTTCTCATAGGCTTCAAATAAAAAGCCTTGCAACCAAACATCACA
ACAAACTTATAAAAGTTTTTTACCTTTTTTAACTTAAGTTAGCC----------------
---------------------------------------------------------TTC
TAGTTGGGGAATATATAAAGTT------------AGTTATTTGATTATTTGGATTCTCCT
TTCTTTTTATAACCCTTTCATCAAGAACTGCCTTCGGAATTGTTGTTAAGGCTTTACGCG
CTTGGCTTGAGGCTGTG-------------------------------------------
-------ACGGATGATGTTCTCTCAAAAACTTCATGACAAAAAAAAAGGAATACCATACA
ATATGTGGTCAACCTCAGGCTCTGAACTTTCAGGTTTTTTGGTTTTTAGCTTTTTTTTTC
TTTCCTCTTTTTCTTAAGTCTTTAGATTTTCTACTGCAGGTTAAAAAAAAAAAAAAGCCT
AAACGGCTGTATCAGAACTTTTTGTTTTGGATTGTAATAAAACATCTGAATAAAGAGATT
GGCTTTACCGTTTTACCGCTGTTGAATTTGTTTTTAAATGCATATCAA
>AT4G36180.1 | Symbols: no symbol available | no full name available | chr4:17119973-17123855 REVERSE LENGTH=3804
-----------------CTTCAAATTATCTACAGAACCAGATTTTTGTATTTCTTTTACT
TTAACTTTACTCTTTTTCTGCTCATTCTCTCTCCCAGAAAAAAACCACACTCAT------
---GG-----------------CGACACTTCTCTCACCTTCTTCAAGC--------TAAG
TTTTCATTTTGTTCACTGCCACAGATCTATGGCCATGGATATATCTCTGTTCTTCATTTT
CCTGGTCATTTACGCGCCGTTAGTCTCATACGCCGATGAATCTCAAGCCGAGATTGATGC
TCTCACGGCGTTTAAACTCAACCTCCATGACCCTCTCGGTGCTTTAACTTCATGGGATCC
TTCAACACCAGCAGCTCCATGTGACTGGCGTGGCGTTGGCTGTACTAACCACCGTGTCAC
TGAGATCCGTCTTCCTCGTCTCCAACTCTCCGGACGAATCTCCGATCGTATCTCCGGTCT
ACGCATGCTACGGAAGCTCAGTCTCCGGTCTAACTCTTTCAACGGTACTATCCCTACTTC
ACTCGCTTACTGCACGCGCCTACTCTCCGTCTTTCTTCAGTACAACTCACTCTCCGGTAA
ACTACCTCCGGCGATGAGGAATCTCACCTCGCTTGAGGTCTTTAACGTCGCTGGAAACCG
TCTCTCCGGTGAGATCCCCGTTGGTTTACCATCGAGTCTCCAGTTCCTTGACATTTCGTC
GAACACCTTCTCTGGTCAGATACCGAGTGGACTCGCTAACTTGACTCAGCTTCAGCTTCT
TAATCTCTCGTATAATCAGTTAACCGGCGAGATTCCGGCGAGTCTAGGTAACCTCCAAAG
TCTTCAGTACTTATGGCTTGATTTCAATCTCTTGCAAGGAACATTACCGTCTGCTATCTC
AAACTGCTCCTCCTTAGTTCACTTGAGCGCGTCGGAGAACGAAATCGGCGGCGTGATTCC
CGCCGCGTACGGTGCTCTTCCGAAACTGGAGGTTCTCTCGCTCTCCAATAACAATTTTTC
CGGTACTGTGCCGTTTTCTCTCTTCTGCAACACATCGCTTACGATTGTTCAGTTAGGGTT
CAATGCTTTCTCCGATATCGTACGGCCTGAGACGACGGCGAACTGTCGTACCGGTTTACA
GGTCTTGGATCTCCAGGAAAATCGAATCTCCGGTCGTTTTCCGTTGTGGTTGACTAATAT
TTTGTCACTAAAGAATCTTGATGTTTCTGGAAACTTGTTTTCCGGTGAGATTCCGCCGGA
TATTGGTAACTTGAAGAGATTAGAGGAACTGAAATTG-GCTAATAACTCTCTTACT--GG
TGAGATTCCTGTTGAGATTAAGCAATGTGGTTCGTTAGATGTTTTAGAT--TTCGAAGGA
AATAGTTTAAAAGGTCAGATTCCAGAATTTCTTGGCTACATGAAGGCTTTAAAGGTTTTA
TCTTTAGGCAGAAACAGCTTCTCAGGTTATGTTCCTTCGTCTATGGTGAATCTGCAGCAG
CTTGAGAGGCTAAACTTAGGTGAAAACAACTTAAATGGGAGTTTTCCGGTGGAGTTGATG
GCGTTGACAAGTCTGTCTGAGCTGGATCTGAGTGGAAATCGGTTTTCCGGGGCAGTTCCG
GTTAGTATCAGCAACTTAAGTAACCTTAGTTTTTTGAATTTGAGTGGGAATGGATTTTCT
GGTGAGATACCAGCTAGTGTAGGCAATCTGTTTAAGTTAACAGCTCTTGATTTGAGCAAG
CAGAATATGTCTGGTGAGGTTCCGGTTGAGCTCTCTGGTTTGCCCAACGTGCAAGTGATT
GCATTGCAGGGAAACAACTTCTCTGGGGTTGTACCTGAAGGGTTTAGTAGCTTGGTGAGT
TTAAGGTATGTGAACCTTAGCTCGAACTCATTCTCCGGGGAAATACCGCAGACTTTTGGG
TTT--CTTCGGTTGTTGGTTTCTTTGTCACTGTCAGATAATCACATCTCTGGGTCTATTC
CACCTGAAATTGGAAACTGCTCAGCTCTTGAAGTTCTTGAGTTAAGATCTAACCGGCTAA
TGGGTCATATTCCAGCTGATCTCTCTCGTCTTCCGCGTTTGAAGGTGCTTGACTTGGGTC
AGAACAACTTGTCAGGCGAAATCCCACCAGAAATCTCTCAGAGCTCGTCTCTCAACTCAT
TGTCACTTGACCACAATCATCTTTCAGGAGTCATACCTGGATCTTTTTCTGGTTTATCAA
ACTTGACAAAGATGGATCTTTCTGTTAATAACTTAACCGGGGAGATTCCGGCTAGCCTCG
CCCTTATTTCTAGTAACCTGGTATACTTCAACGTCTCAAGCAACAACCTTAAAGGAGAGA
TTCCAGCTTCTTTAGGCTCAAGAATCAACAACACATCAGAATTTTCAGGCAACACAGAGC
TCTGCGGGAAGCCATTGAACAGAAGATGTGAAAGCAGCACAGCGGAGGGGAAGAAGAAGA
AAAGGAAAATGATTCTGATGATAGTTATGGCTGCAATTGGTGCATTCCTCTTGTCACTCT
TCTGCTGC--TTCTACGTTTACACACTCTTGAAATGGAGGAAGAAGCTGAAACAACAGTC
TACAACGGGAGAGAAGAAACGCAGTCCTGGTAGAACAAGCGCAGGAAGTAGAGT------
-------TCGTAGCAGCACAAGCAGATCAAGCACAGAAAACGGAGAACCAAAGCTAGTGA
TGTTCAATAACAAGATCACTCTAGCTGAAACAATTGAAGCAACACGACAGTTCGATGAAG
AAAACGTTCTTAGCAGA-ACCCGATATGGATTGCTATTTAAAGCCAATTACAATGACGGA
ATGGTTCTCTCTATCCGCCGCTTACCCAATGGATCACTCTTAAATGAGAACTTGTTCAAA
AAGGAAGCCGAAGTTCTTGGTAAAGTCAAGCACCGAAACATCACAGTCCTTAGAGGTTAC
TACGCAGGTCC-------ACCAGA--TTTAAGGCTTTTGGTATATGACTACATGCCCAAT
GGGAACTTATCTACCCTGCTCCAAGAAGCTTCCCACCAAGATGGCCATGTCCTAAACTGG
CCAATGCGCCACCTCATAGCTCTCGGGATCGCGCGCGGACTCGGATTCCTCCATCAATCC
AACATGGTTCATGGTGATATCAAGCCACAGAATGTACTCTTCGACGCTGACTTTGAAGCC
CATATATCTGATTTCGGGCTTGACCGTCTCACAATTCGATCCCCATCAAGATCAGCCGTC
ACAGCAAACACCATTGGGACACTAGGATATGTCTCTCCAGAAGCCACATTG--TCCGGGG
AAATCACAAGAGAATCTGACATCTACAGCTTCGGCATTGTCCTACTCGAAATCCTAACTG
GAAAAAGACCAGTAATGTTCACACAAGACGAGGATATAGTGAAATGGGTAAAGAAACAGC
TTCAGAGAGGTCAAGTTACAGAGCTACTAGAACCAGGACTACTCGAACTTGACCCGGAAT
CATCAGAATGGGA---AGAGTTCTTATTAGGAATCAAAGTCGGACTTCTTTGTACTGCAA
CAGATCCTCTAGACCGTCCAACAATGTCCGATGTTGTTTTCATGCTTGAAGGCTGTCGTG
TTGGTCCTGACGTTCCTTCCTCCGCCGACCCAACCTCTCAGCCTTCACCGGCCTAACCGT
TTTTCTTATTTTTAGTCTTCCTGATTTAAACTGTTAGTCAAAAACAAAAAACAAAAAACA
AGAAGCAATTATTAAAAATTTCAGCAGT-----ATTTATTGGTCTTTGGAGCTTCTTTAA
TGTCTTTTGTT-----------------------------------TGGACCAAGAAGTT
GAATTAAATTGTTGTTACAATCTCGAGTGGTCCACTAGAGATTATCTATC----------
------AGTCAAACGTAATTAACGCATCCGGGATTTGATGCATGTGGG
