import random
a=random.randrange(0,10)
b=random.randrange(0,10)
c=random.randrange(0,10)
d=random.randrange(0,10)
e=random.randrange(0,10)
f=random.randrange(0,10)
g=random.randrange(0,10)
h=random.randrange(0,10)
A=str(a)
B=str(b)
C=str(c)
D=str(d)
E=str(e)
F=str(f)
G=str(g)
H=str(h)
print("교환 비밀번호는 "+A+B+C+D+" "+E+F+G+H+" 입니다")